version: '3'
services:
  spark-master:
    image: ibodrin/spark-lab:streaming-v1
    hostname: spark-test1
    ports:
      - "8080:8080"
      - "4040:4040"
      - "8888:8888"
    volumes:
      - spark-data:/data
    networks:
      - sparknet
    command: >
      bash -c "
        apt-get -y update && apt-get -y upgrade &&
        apt-get install -y vim tree mlocate pip python3 default-jdk rsyslog acl git ssh &&
        service ssh start &&
        setfacl -m u:spark:rwx /opt &&
        echo 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64 >> /etc/profile' &&
        echo 'export PATH=$PATH:/opt/hadoop-3.3.6/bin'
        sleep 1
        su - spark bash -c 'eval $(ssh-agent) && ssh-add ~/.ssh/git_read && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts && git clone git@github.com:ibodrin/spark-streaming-sample.git && ~/spark-streaming-sample/scripts/misc/install_dependencies.sh && ~/spark-streaming-sample/scripts/misc/start_all.sh' &&
        tail -f /dev/null"

networks:
  sparknet:
    driver: bridge

volumes:
  spark-data:
